site_name: SaiunCLI ✨
site_url: https://erickkbentz.github.io/SaiunCLI/
repo_url: https://github.com/Erickkbentz/SaiunCLI
nav:
  - Home: index.md
  - Reference:
      - CLI: reference/cli.md
      - Command: reference/command.md
      - Option: reference/option.md
      - Argument: reference/argument.md
      - Theme: reference/theme.md
      - Console: reference/console.md


plugins:
- search
- mkdocstrings:
    handlers:
      python:
        options:
          docstring_options:
            ignore_init_summary: true
          docstring_section_style: list
          filters: ["!^_"]
          heading_level: 1
          inherited_members: true
          merge_init_into_class: true
          parameter_headings: true
          preload_modules: [mkdocstrings]
          relative_crossrefs: true
          scoped_crossrefs: true
          separate_signature: true
          show_bases: false
          show_inheritance_diagram: true
          show_root_heading: true
          show_root_full_path: false
          show_signature_annotations: true
          show_source: true
          show_symbol_type_heading: true
          show_symbol_type_toc: true
          show_inheritance_diagram: true
          signature_crossrefs: true
          summary: true
          unwrap_annotated: true

theme:
  name: material
  palette:
    - scheme: slate
      primary: blue-grey
      accent: light-blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - scheme: default
      primary: blue-grey
      accent: light-blue
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
  features:
    - content.code.annotate
    - content.code.copy
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true
      pygments_lang_class: true
      pygments_style: "monokai"
  - pymdownx.inlinehilite
  - pymdownx.snippets
